### ISSUE TITLE
Integer DSP

### ISSUE THREAD

**Issue by jordens** [tarcieri/micromath#93]
We have a bunch of high-performance DSP algorithms and functions in https://github.com/quartiq/stabilizer/tree/master/dsp/src and would like to factor them out for wider usage.
Before we get started with that, I wonder whether `micromath` is a good place for them. It matches the mission statement ("Optimizes for performance and small code size at the cost of precision.") but is predominantly integer-oriented (apart from the `f32` IIR filter).
Opinions?

**Comment by tarcieri** [comment]
Interesting question. Pretty much everything in Micromath currently is `f32`-oriented, but there's no reason it has to stay that way.

Certainly something to consider.

**Comment by TDHolmes** [comment]
@jordens is there still interest in this, or are you guys sticking with [`idsp`](https://github.com/quartiq/idsp)?

**Comment by jordens** [comment]
It currently seems wise to keep it a separate. Well probably revise the APIs as well. And in any case I think it should remain a separate crate from the other num/micro crates. It's a reasonably well distinguishable thing.
Feel free to close.

**Comment by tarcieri** [comment]
Sounds good
